[tool.poetry]
name = "api"
version = "0.0.0"
description = ""
authors = ["Guillaume Chervet <guillaume.chervet@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
pymupdf = "1.23.3"
keras = "2.12.0"
tensorflow = "2.12.0"
fastapi = "0.95.0"
opencv-contrib-python-headless = "4.8.0.76"
tensorflow-io-gcs-filesystem = "0.27.0"
uvicorn = "0.23.2"
python-multipart = "0.0.6"
pillow = "10.0.1"
mlopspython-inference = {path = "packages/inference"}
mlopspython-extraction = {path = "packages/extraction"}

[tool.poetry.group.dev.dependencies]
coverage = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
