# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
name: label_split_data_environment
conda_file:
  name: default_environment
  channels:
    - defaults
  dependencies:
    - python=3.10
    #- pip=22.3.1
    - pip:
      - mldesigner==0.1.0b4
      - matplotlib
      - keras
      - numpy
      - tensorflow
      - scipy
      - opencv-contrib-python-headless==4.7.0.68
      - mlflow
      - azureml-mlflow
      - ./packages/inference-0.0.0-py3-none-any.whl